### ISSUE TITLE
shape problem

### ISSUE THREAD

**Issue by seogihyun** [MaximeBataille/tennis_tracking#4]
![캡처](https://user-images.githubusercontent.com/72849922/138662533-268d2709-62ec-4659-b6d2-85d914e367c2.PNG)

I got a model_baddy.h5 file from weekenddeeplearning because your model.1 file does not operate.
However there is other problem "Cannot assign to variable conv2d/kernel:0 due to variable shape (3, 3, 3, 64) and value shape (64, 9, 3, 3) are incompatible".

I want to fix the shape.
Please let me know.

**Comment by Yasminbr** [comment]
Hey im isuuimg the same problem in my code too . 
![image](https://user-images.githubusercontent.com/48754298/145362430-2b1f08c3-6513-4dff-b093-3c84750a8893.png)

**Comment by Q2Learn** [comment]
I had the same problem and I had to check all the file names because some were Capital and some we Non Capital. Also some file names had a '/' in front of it so make sure your directory location is good as well as the file and folder names. 

For example some files were Yolov3 instead of the yolov3 and '/VideoOutput' instead of 'video_output':

After changing my files and folders I have it working with:

!python3 "predict_video.py"  --save_weights_path="weights_tracknet/model.1" --input_video_path="VideoInput/video_cut.mp4" --output_video_path="VideoOutput/video_output_MyTest.avi" --n_classes=256 --path_yolo_classes="yolov3/yolov3.txt" --path_yolo_weights="yolov3/yolov3.weights" --path_yolo_config="yolov3/yolov3.cfg"

Also check in file predict_video.py on line 66 that it's 'modelFN = trackNet' and not 'modelFN = tracknet'

**Comment by Gi-gigi** [comment]
Hi @Q2Learn friend, I updated my path, but also ocurred:
```
`Traceback (most recent call last):
  File "tennis_tracking/predict_video.py", line 109, in <module>outs = net.forward(get_output_layers(net))
  File "tennis_tracking/TrackPlayers/trackplayers.py", line 10, in get_output_layers output_layers = [layer_names[i[0] - 1] 
for i in net.getUnconnectedOutLayers()]
  File "tennis_tracking/TrackPlayers/trackplayers.py", line 10, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

IndexError: invalid index to scalar variable.`
```

can u help me how to fix it?  thank u~

**Comment by Q2Learn** [comment]
Hey,

I’m not sure. I haven’t worked with this algorithm in a while. And I’m not familiar with it. But check all your paths are correct in the code base because it’s looking for the model weights in specific locations. That’s how I got it to work anyhow.

**Comment by Gi-gigi** [comment]
Hey friend @Q2Learn.
One more question, do u run this project on google colab? or personal PC?
